version: "3.8"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_mcp
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-password}
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test:
        [
          "CMD",
          "cypher-shell",
          "-u",
          "${NEO4J_USER:-neo4j}",
          "-p",
          "${NEO4J_PASSWORD:-password}",
          "RETURN 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  mcp-server:
    build: .
    container_name: mcp_server
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j:7687}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
      - NEO4J_DATABASE=${NEO4J_DATABASE:-neo4j}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
